dist: xenial
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-full
script:
  - cd specification
  - make
deploy:
  provider: releases
  api_key:
    secure: $DEPLOY_KEY
  skip_cleanup: true
  on:
    repo: mit-mit/language
    branch: pdfspec
